-- Extended profile fields for creators
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INT CHECK (age IS NULL OR (age >= 13 AND age <= 120));
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS occupation VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS hobbies TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS brands_liked TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
